const DDB_CONFIG = {
  sources: [
    { id: 1, name: "BR", description: "Basic Rules", sourceCategoryId: 1, isReleased: true },
    { id: 2, name: "PHB", description: "Player's Handbook", sourceCategoryId: 1, isReleased: true },
    { id: 3, name: "DMG", description: "Dungeon Master's Guide", sourceCategoryId: 1, isReleased: true },
    { id: 4, name: "EE", description: "Elemental Evil Player's Companion", sourceCategoryId: 1, isReleased: true },
    { id: 5, name: "MM", description: "Monster Manual", sourceCategoryId: 1, isReleased: true },
    { id: 6, name: "CoS", description: "Curse of Strahd", sourceCategoryId: 1, isReleased: true },
    { id: 7, name: "HotDQ", description: "Hoard of the Dragon Queen", sourceCategoryId: 1, isReleased: true },
    { id: 8, name: "LMoP", description: "Lost Mine of Phandelver", sourceCategoryId: 1, isReleased: true },
    { id: 9, name: "OotA", description: "Out of the Abyss", sourceCategoryId: 1, isReleased: true },
    { id: 10, name: "PotA", description: "Princes of the Apocalypse", sourceCategoryId: 1, isReleased: true },
    { id: 11, name: "RoT", description: "Rise of Tiamat", sourceCategoryId: 1, isReleased: true },
    { id: 12, name: "SKT", description: "Storm King's Thunder", sourceCategoryId: 1, isReleased: true },
    { id: 13, name: "SCAG", description: "Sword Coast Adventurer's Guide", sourceCategoryId: 1, isReleased: true },
    { id: 14, name: "TftYP", description: "Tales from the Yawning Portal", sourceCategoryId: 1, isReleased: true },
    { id: 15, name: "VGtM", description: "Volo's Guide to Monsters", sourceCategoryId: 1, isReleased: true },
    { id: 16, name: "TSC", description: "The Sunless Citadel", sourceCategoryId: 1, isReleased: true },
    { id: 17, name: "TFoF", description: "The Forge of Fury", sourceCategoryId: 1, isReleased: true },
    { id: 18, name: "THSoT", description: "The Hidden Shrine of Tamoachan", sourceCategoryId: 1, isReleased: true },
    { id: 19, name: "WPM", description: "White Plume Mountain", sourceCategoryId: 1, isReleased: true },
    { id: 20, name: "DiT", description: "Dead in Thay", sourceCategoryId: 1, isReleased: true },
    { id: 21, name: "AtG", description: "Against the Giants", sourceCategoryId: 1, isReleased: true },
    { id: 22, name: "ToH", description: "Tomb of Horrors", sourceCategoryId: 1, isReleased: true },
    { id: 25, name: "ToA", description: "Tomb of Annihilation", sourceCategoryId: 1, isReleased: true },
    { id: 26, name: "CoSCO", description: "Curse of Strahd: Character Options", sourceCategoryId: 1, isReleased: true },
    { id: 27, name: "XGtE", description: "Xanathar's Guide to Everything", sourceCategoryId: 1, isReleased: true },
    { id: 28, name: "TTP", description: "The Tortle Package", sourceCategoryId: 1, isReleased: true },
    { id: 29, name: "UA", description: "Unearthed Arcana", sourceCategoryId: 3, isReleased: true },
    { id: 30, name: "DDB", description: "D&amp;D Beyond", sourceCategoryId: 1, isReleased: false },
    { id: 31, name: "CR", description: "Critical Role", sourceCategoryId: 2, isReleased: true },
    { id: 32, name: "TCS", description: "Tal'Dorei Campaign Setting", sourceCategoryId: 1, isReleased: false },
    { id: 33, name: "MToF", description: "Mordenkainen’s Tome of Foes", sourceCategoryId: 1, isReleased: true },
    { id: 34, name: "DDIA-MORD", description: "Rrakkma", sourceCategoryId: 12, isReleased: true },
    { id: 35, name: "WDH", description: "Waterdeep: Dragon Heist", sourceCategoryId: 1, isReleased: true },
    {
      id: 36,
      name: "WDotMM",
      description: "Waterdeep: Dungeon of the Mad Mage",
      sourceCategoryId: 1,
      isReleased: true,
    },
    { id: 37, name: "WGtE", description: "Wayfinder's Guide to Eberron", sourceCategoryId: 8, isReleased: true },
    { id: 38, name: "GGtR", description: "Guildmasters' Guide to Ravnica", sourceCategoryId: 7, isReleased: true },
    { id: 39, name: "_APT", description: "Archived Playtest", sourceCategoryId: 9, isReleased: false },
    { id: 40, name: "LLoK", description: "Lost Laboratory of Kwalish", sourceCategoryId: 12, isReleased: true },
    { id: 41, name: "DoIP", description: "Dragon of Icespire Peak", sourceCategoryId: 1, isReleased: true },
    { id: 42, name: "TMR", description: "Tactical Maps Reincarnated", sourceCategoryId: 1, isReleased: true },
    { id: 43, name: "GoS", description: "Ghosts of Saltmarsh", sourceCategoryId: 1, isReleased: true },
    { id: 44, name: "AI", description: "Acquisitions Incorporated", sourceCategoryId: 1, isReleased: true },
    { id: 47, name: "HftT", description: "Hunt for the Thessalhydra", sourceCategoryId: 1, isReleased: true },
    {
      id: 48,
      name: "BGDiA",
      description: "Baldur's Gate: Descent into Avernus",
      sourceCategoryId: 1,
      isReleased: true,
    },
    { id: 49, name: "ERftLW", description: "Eberron: Rising from the Last War", sourceCategoryId: 8, isReleased: true },
    { id: 50, name: "SLW", description: "Storm Lord’s Wrath", sourceCategoryId: 1, isReleased: true },
    { id: 51, name: "SDW", description: "Sleeping Dragon’s Wake", sourceCategoryId: 1, isReleased: true },
    { id: 52, name: "DC", description: "Divine Contention", sourceCategoryId: 1, isReleased: true },
    { id: 53, name: "SAC", description: "Sage Advice Compendium", sourceCategoryId: 1, isReleased: true },
    {
      id: 54,
      name: "DDvRaM",
      description: "Dungeons &amp; Dragons vs. Rick and Morty",
      sourceCategoryId: 10,
      isReleased: true,
    },
    { id: 55, name: "LR", description: "Locathah Rising", sourceCategoryId: 12, isReleased: true },
    { id: 56, name: "IMR", description: "Infernal Machine Rebuild", sourceCategoryId: 12, isReleased: true },
    {
      id: 57,
      name: "MFFV1",
      description: "Mordenkainen's Fiendish Folio Volume 1",
      sourceCategoryId: 12,
      isReleased: true,
    },
    { id: 58, name: "SD", description: "Sapphire Dragon", sourceCategoryId: 1, isReleased: true },
    { id: 59, name: "EGtW", description: "Explorer's Guide to Wildemount", sourceCategoryId: 2, isReleased: true },
    { id: 60, name: "OGA", description: "One Grung Above", sourceCategoryId: 12, isReleased: true },
    { id: 61, name: "MOoT", description: "Mythic Odysseys of Theros", sourceCategoryId: 7, isReleased: true },
    { id: 62, name: "WA", description: "Frozen Sick", sourceCategoryId: 2, isReleased: true },
    { id: 63, name: "TSCF", description: "The Sunless Citadel (Free)", sourceCategoryId: 1, isReleased: false },
    { id: 64, name: "TFoFF", description: "The Forge of Fury (Free)", sourceCategoryId: 1, isReleased: false },
    {
      id: 65,
      name: "LRDToB",
      description: "Legends of Runeterra: Dark Tides of Bilgewater",
      sourceCategoryId: 11,
      isReleased: false,
    },
    {
      id: 66,
      name: "IDRotF",
      description: "Icewind Dale: Rime of the Frostmaiden",
      sourceCategoryId: 1,
      isReleased: true,
    },
    { id: 67, name: "TCoE", description: "Tasha’s Cauldron of Everything", sourceCategoryId: 1, isReleased: true },
    { id: 68, name: "CM", description: "Candlekeep Mysteries", sourceCategoryId: 1, isReleased: true },
    { id: 69, name: "VRGtR", description: "Van Richten’s Guide to Ravenloft", sourceCategoryId: 1, isReleased: false },
  ]
};
exports.DDB_CONFIG = DDB_CONFIG;
