name: Build/release

on:
  push:
    tags: 
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}


  notify:
    needs: release

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ubuntu-latest]

    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_HOOK }}
          DISCORD_USERNAME: "Release-O-Bot"
        uses: Ilshidur/action-discord@0.0.2
        with:
          args: 'DDB Adventure Muncher ${{ steps.get-version.outputs.version }} has been marked as draft. Release imminent...'

