name: Notify on release

on:
  release:
    types: 
     - released

jobs:
  notify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_HOOK }}
          DISCORD_USERNAME: "Smol - Head of QA"
        uses: Ilshidur/action-discord@0.0.2
        with:
          args: "The release kobolds have pushed DDB Adventure Muncher ${{ steps.get-version.outputs.version }} to it's release page."

